create extension if not exists pgcrypto;
create type public.app_role as enum ('admin','manager','cashier','technician');
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade, full_name text not null, role public.app_role not null default 'cashier', active boolean not null default true, created_at timestamptz not null default now());
create table public.products(id uuid primary key default gen_random_uuid(), name text not null, category text not null check(category in ('phone','speaker','accessory','repair_part')), storage text, barcode text unique, imei text, cost numeric(10,2) not null default 0, price numeric(10,2) not null default 0, old_price numeric(10,2), minimum_price numeric(10,2) not null default 0, quantity integer not null default 0, image_url text, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.carrier_plans(id uuid primary key default gen_random_uuid(), name text not null, starting_price numeric(10,2) not null, image_url text, is_active boolean not null default true);
create table public.customers(id uuid primary key default gen_random_uuid(), full_name text not null, phone text not null, email text, notes text, created_at timestamptz not null default now());
create table public.repair_tickets(id uuid primary key default gen_random_uuid(), ticket_number text unique not null, customer_id uuid references public.customers(id), device text not null, imei_serial text, issue text not null, status text not null default 'waiting', assigned_to uuid references public.profiles(id), quoted_price numeric(10,2), private_notes text, created_at timestamptz not null default now());
create table public.sales(id uuid primary key default gen_random_uuid(), employee_id uuid not null references public.profiles(id), subtotal numeric(10,2) not null, tax numeric(10,2) not null default 0, total numeric(10,2) not null, payment_method text not null check(payment_method in ('cash','card','split','store_credit')), card_last4 text check(card_last4 is null or card_last4 ~ '^[0-9]{4}$'), created_at timestamptz not null default now());
create table public.sale_items(id uuid primary key default gen_random_uuid(), sale_id uuid not null references public.sales(id) on delete cascade, product_id uuid references public.products(id), description text not null, quantity integer not null check(quantity>0), unit_price numeric(10,2) not null, original_price numeric(10,2) not null, approved_by uuid references public.profiles(id));
create table public.audit_log(id bigint generated always as identity primary key, actor_id uuid references public.profiles(id), action text not null, table_name text not null, record_id text, payload jsonb, created_at timestamptz not null default now());
create view public.products_public as select id,name,category,storage,price,old_price,quantity,image_url,is_active from public.products where is_active=true;
create view public.carrier_plans_public as select * from public.carrier_plans where is_active=true;
alter table public.profiles enable row level security; alter table public.products enable row level security; alter table public.carrier_plans enable row level security; alter table public.customers enable row level security; alter table public.repair_tickets enable row level security; alter table public.sales enable row level security; alter table public.sale_items enable row level security; alter table public.audit_log enable row level security;
create or replace function public.current_role() returns public.app_role language sql stable security definer set search_path=public as $$ select role from public.profiles where id=auth.uid() and active=true $$;
create policy "public can read active products" on public.products for select using (is_active=true or auth.uid() is not null);
create policy "public can read active carriers" on public.carrier_plans for select using (is_active=true or auth.uid() is not null);
create policy "staff read own profile" on public.profiles for select using (id=auth.uid() or public.current_role() in ('admin','manager'));
create policy "admin manage profiles" on public.profiles for all using (public.current_role()='admin') with check (public.current_role()='admin');
create policy "manager manage products" on public.products for all using (public.current_role() in ('admin','manager')) with check (public.current_role() in ('admin','manager'));
create policy "manager manage carriers" on public.carrier_plans for all using (public.current_role() in ('admin','manager')) with check (public.current_role() in ('admin','manager'));
create policy "staff read customers" on public.customers for select using (public.current_role() in ('admin','manager','cashier','technician'));
create policy "staff insert customers" on public.customers for insert with check (public.current_role() in ('admin','manager','cashier','technician'));
create policy "manager update customers" on public.customers for update using (public.current_role() in ('admin','manager'));
create policy "repair staff tickets" on public.repair_tickets for select using (public.current_role() in ('admin','manager') or assigned_to=auth.uid() or public.current_role()='cashier');
create policy "staff create tickets" on public.repair_tickets for insert with check (public.current_role() in ('admin','manager','cashier','technician'));
create policy "assigned update tickets" on public.repair_tickets for update using (public.current_role() in ('admin','manager') or assigned_to=auth.uid());
create policy "staff insert sales" on public.sales for insert with check (employee_id=auth.uid() and public.current_role() in ('admin','manager','cashier'));
create policy "staff read permitted sales" on public.sales for select using (public.current_role() in ('admin','manager') or employee_id=auth.uid());
create policy "staff insert sale items" on public.sale_items for insert with check (public.current_role() in ('admin','manager','cashier'));
create policy "staff read sale items" on public.sale_items for select using (public.current_role() in ('admin','manager','cashier'));
create policy "admin audit read" on public.audit_log for select using (public.current_role()='admin');
revoke all on public.customers,public.repair_tickets,public.sales,public.sale_items,public.audit_log from anon;
grant select on public.products_public,public.carrier_plans_public to anon,authenticated;
grant select,insert,update,delete on public.products,public.carrier_plans to authenticated;
grant select,insert,update on public.customers,public.repair_tickets to authenticated;
grant select,insert on public.sales,public.sale_items to authenticated;
grant select on public.audit_log to authenticated;
